// <auto-generated />
using System;
using Kolokwium_s22884.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium_s22884.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium_s22884.Models.BackPackSlot", b =>
                {
                    b.Property<int>("PkBackpack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkBackpack"));

                    b.Property<int>("IdCharacter")
                        .HasColumnType("int")
                        .HasColumnName("Fk_character");

                    b.Property<int>("IdItem")
                        .HasColumnType("int")
                        .HasColumnName("Fk_item");

                    b.HasKey("PkBackpack");

                    b.HasIndex("IdCharacter");

                    b.HasIndex("IdItem");

                    b.ToTable("BackPack_Slots");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.Character", b =>
                {
                    b.Property<int>("PkCharacter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCharacter"));

                    b.Property<int>("CurrentWeig")
                        .HasColumnType("int")
                        .HasColumnName("current_weig");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int")
                        .HasColumnName("max_weight");

                    b.Property<int>("Money")
                        .HasColumnType("int")
                        .HasColumnName("money");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("PkCharacter");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.CharacterTitle", b =>
                {
                    b.Property<int>("IdCharacter")
                        .HasColumnType("int")
                        .HasColumnName("FK_charact");

                    b.Property<int>("IdTitle")
                        .HasColumnType("int")
                        .HasColumnName("FK_title");

                    b.Property<DateTime>("AquireAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("aquire_at");

                    b.HasKey("IdCharacter", "IdTitle");

                    b.HasIndex("IdTitle");

                    b.ToTable("Characters_Titles");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.Item", b =>
                {
                    b.Property<int>("PkItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkItem"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weig");

                    b.HasKey("PkItem");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.Title", b =>
                {
                    b.Property<int>("PkTitle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkTitle"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nam");

                    b.HasKey("PkTitle");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.BackPackSlot", b =>
                {
                    b.HasOne("Kolokwium_s22884.Models.Character", "Character")
                        .WithMany("BackpackSlots")
                        .HasForeignKey("IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_s22884.Models.Item", "Item")
                        .WithMany("BackpackSlots")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.CharacterTitle", b =>
                {
                    b.HasOne("Kolokwium_s22884.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("IdCharacter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium_s22884.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("IdTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.Character", b =>
                {
                    b.Navigation("BackpackSlots");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.Item", b =>
                {
                    b.Navigation("BackpackSlots");
                });

            modelBuilder.Entity("Kolokwium_s22884.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
